# Generated by Django 5.1.7 on 2025-03-20 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('overdue', 'Overdue'), ('due_today', 'Due Today')], default='upcoming', max_length=20),
        ),
    ]
